development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: avmoney
  suffix: development
  username: admin
  password: admin

test:
  <<: *development
  suffix: test

production:
  protocol: 'https'
  host: aptos.cloudant.com
  port: 443
  prefix: avmoney
  suffix: production
  username: aptos
  password: wry246WRY